// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: v1/pkg/contract/service.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Identification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	FolderID string `protobuf:"bytes,2,opt,name=FolderID,proto3" json:"FolderID,omitempty"`
	ClientID string `protobuf:"bytes,3,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
}

func (x *Identification) Reset() {
	*x = Identification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pkg_contract_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Identification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identification) ProtoMessage() {}

func (x *Identification) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pkg_contract_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identification.ProtoReflect.Descriptor instead.
func (*Identification) Descriptor() ([]byte, []int) {
	return file_v1_pkg_contract_service_proto_rawDescGZIP(), []int{0}
}

func (x *Identification) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Identification) GetFolderID() string {
	if x != nil {
		return x.FolderID
	}
	return ""
}

func (x *Identification) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

type StandardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status      int32  `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
}

func (x *StandardResponse) Reset() {
	*x = StandardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pkg_contract_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StandardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandardResponse) ProtoMessage() {}

func (x *StandardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pkg_contract_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandardResponse.ProtoReflect.Descriptor instead.
func (*StandardResponse) Descriptor() ([]byte, []int) {
	return file_v1_pkg_contract_service_proto_rawDescGZIP(), []int{1}
}

func (x *StandardResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *StandardResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identification *Identification `protobuf:"bytes,1,opt,name=Identification,proto3" json:"Identification,omitempty"`
	Path           string          `protobuf:"bytes,2,opt,name=Path,proto3" json:"Path,omitempty"`
	Hash           string          `protobuf:"bytes,3,opt,name=Hash,proto3" json:"Hash,omitempty"`
	ModTime        int64           `protobuf:"varint,4,opt,name=ModTime,proto3" json:"ModTime,omitempty"`
	Size           int64           `protobuf:"varint,5,opt,name=Size,proto3" json:"Size,omitempty"`
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pkg_contract_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pkg_contract_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_v1_pkg_contract_service_proto_rawDescGZIP(), []int{2}
}

func (x *File) GetIdentification() *Identification {
	if x != nil {
		return x.Identification
	}
	return nil
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *File) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

func (x *File) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Folder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identification *Identification `protobuf:"bytes,1,opt,name=Identification,proto3" json:"Identification,omitempty"`
	Path           string          `protobuf:"bytes,2,opt,name=Path,proto3" json:"Path,omitempty"`
	ModTime        int64           `protobuf:"varint,3,opt,name=ModTime,proto3" json:"ModTime,omitempty"`
}

func (x *Folder) Reset() {
	*x = Folder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pkg_contract_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Folder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Folder) ProtoMessage() {}

func (x *Folder) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pkg_contract_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Folder.ProtoReflect.Descriptor instead.
func (*Folder) Descriptor() ([]byte, []int) {
	return file_v1_pkg_contract_service_proto_rawDescGZIP(), []int{3}
}

func (x *Folder) GetIdentification() *Identification {
	if x != nil {
		return x.Identification
	}
	return nil
}

func (x *Folder) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Folder) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

type RenameInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	NewPath string `protobuf:"bytes,2,opt,name=NewPath,proto3" json:"NewPath,omitempty"`
}

func (x *RenameInfo) Reset() {
	*x = RenameInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pkg_contract_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameInfo) ProtoMessage() {}

func (x *RenameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pkg_contract_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameInfo.ProtoReflect.Descriptor instead.
func (*RenameInfo) Descriptor() ([]byte, []int) {
	return file_v1_pkg_contract_service_proto_rawDescGZIP(), []int{4}
}

func (x *RenameInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RenameInfo) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

type CreateFolderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identification *Identification `protobuf:"bytes,1,opt,name=Identification,proto3" json:"Identification,omitempty"`
	Folder         *Folder         `protobuf:"bytes,2,opt,name=Folder,proto3" json:"Folder,omitempty"`
}

func (x *CreateFolderReq) Reset() {
	*x = CreateFolderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pkg_contract_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFolderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFolderReq) ProtoMessage() {}

func (x *CreateFolderReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pkg_contract_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFolderReq.ProtoReflect.Descriptor instead.
func (*CreateFolderReq) Descriptor() ([]byte, []int) {
	return file_v1_pkg_contract_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateFolderReq) GetIdentification() *Identification {
	if x != nil {
		return x.Identification
	}
	return nil
}

func (x *CreateFolderReq) GetFolder() *Folder {
	if x != nil {
		return x.Folder
	}
	return nil
}

type RenameFolderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identification *Identification `protobuf:"bytes,1,opt,name=Identification,proto3" json:"Identification,omitempty"`
	RenameInfo     *RenameInfo     `protobuf:"bytes,2,opt,name=RenameInfo,proto3" json:"RenameInfo,omitempty"`
	ModTime        int64           `protobuf:"varint,3,opt,name=ModTime,proto3" json:"ModTime,omitempty"`
}

func (x *RenameFolderReq) Reset() {
	*x = RenameFolderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pkg_contract_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenameFolderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameFolderReq) ProtoMessage() {}

func (x *RenameFolderReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pkg_contract_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameFolderReq.ProtoReflect.Descriptor instead.
func (*RenameFolderReq) Descriptor() ([]byte, []int) {
	return file_v1_pkg_contract_service_proto_rawDescGZIP(), []int{6}
}

func (x *RenameFolderReq) GetIdentification() *Identification {
	if x != nil {
		return x.Identification
	}
	return nil
}

func (x *RenameFolderReq) GetRenameInfo() *RenameInfo {
	if x != nil {
		return x.RenameInfo
	}
	return nil
}

func (x *RenameFolderReq) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

type DeleteFolderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identification *Identification `protobuf:"bytes,1,opt,name=Identification,proto3" json:"Identification,omitempty"`
	Path           string          `protobuf:"bytes,2,opt,name=Path,proto3" json:"Path,omitempty"`
}

func (x *DeleteFolderReq) Reset() {
	*x = DeleteFolderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pkg_contract_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFolderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFolderReq) ProtoMessage() {}

func (x *DeleteFolderReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pkg_contract_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFolderReq.ProtoReflect.Descriptor instead.
func (*DeleteFolderReq) Descriptor() ([]byte, []int) {
	return file_v1_pkg_contract_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteFolderReq) GetIdentification() *Identification {
	if x != nil {
		return x.Identification
	}
	return nil
}

func (x *DeleteFolderReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RecoverFolderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identification *Identification `protobuf:"bytes,1,opt,name=Identification,proto3" json:"Identification,omitempty"`
	Path           string          `protobuf:"bytes,2,opt,name=Path,proto3" json:"Path,omitempty"`
}

func (x *RecoverFolderReq) Reset() {
	*x = RecoverFolderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pkg_contract_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecoverFolderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverFolderReq) ProtoMessage() {}

func (x *RecoverFolderReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pkg_contract_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverFolderReq.ProtoReflect.Descriptor instead.
func (*RecoverFolderReq) Descriptor() ([]byte, []int) {
	return file_v1_pkg_contract_service_proto_rawDescGZIP(), []int{8}
}

func (x *RecoverFolderReq) GetIdentification() *Identification {
	if x != nil {
		return x.Identification
	}
	return nil
}

func (x *RecoverFolderReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetDirSchemaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identification *Identification `protobuf:"bytes,1,opt,name=Identification,proto3" json:"Identification,omitempty"`
}

func (x *GetDirSchemaReq) Reset() {
	*x = GetDirSchemaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pkg_contract_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDirSchemaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirSchemaReq) ProtoMessage() {}

func (x *GetDirSchemaReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pkg_contract_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirSchemaReq.ProtoReflect.Descriptor instead.
func (*GetDirSchemaReq) Descriptor() ([]byte, []int) {
	return file_v1_pkg_contract_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetDirSchemaReq) GetIdentification() *Identification {
	if x != nil {
		return x.Identification
	}
	return nil
}

type GetDirSchemaResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StandardResponse *StandardResponse `protobuf:"bytes,1,opt,name=StandardResponse,proto3" json:"StandardResponse,omitempty"`
	Folders          []*Folder         `protobuf:"bytes,2,rep,name=Folders,proto3" json:"Folders,omitempty"`
	Files            []*File           `protobuf:"bytes,3,rep,name=Files,proto3" json:"Files,omitempty"`
}

func (x *GetDirSchemaResp) Reset() {
	*x = GetDirSchemaResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pkg_contract_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDirSchemaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirSchemaResp) ProtoMessage() {}

func (x *GetDirSchemaResp) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pkg_contract_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirSchemaResp.ProtoReflect.Descriptor instead.
func (*GetDirSchemaResp) Descriptor() ([]byte, []int) {
	return file_v1_pkg_contract_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetDirSchemaResp) GetStandardResponse() *StandardResponse {
	if x != nil {
		return x.StandardResponse
	}
	return nil
}

func (x *GetDirSchemaResp) GetFolders() []*Folder {
	if x != nil {
		return x.Folders
	}
	return nil
}

func (x *GetDirSchemaResp) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

type GetFolderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identification *Identification `protobuf:"bytes,1,opt,name=Identification,proto3" json:"Identification,omitempty"`
	Path           string          `protobuf:"bytes,2,opt,name=Path,proto3" json:"Path,omitempty"`
}

func (x *GetFolderReq) Reset() {
	*x = GetFolderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pkg_contract_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFolderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFolderReq) ProtoMessage() {}

func (x *GetFolderReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pkg_contract_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFolderReq.ProtoReflect.Descriptor instead.
func (*GetFolderReq) Descriptor() ([]byte, []int) {
	return file_v1_pkg_contract_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetFolderReq) GetIdentification() *Identification {
	if x != nil {
		return x.Identification
	}
	return nil
}

func (x *GetFolderReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetFolderResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File []*File `protobuf:"bytes,1,rep,name=File,proto3" json:"File,omitempty"`
}

func (x *GetFolderResp) Reset() {
	*x = GetFolderResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pkg_contract_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFolderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFolderResp) ProtoMessage() {}

func (x *GetFolderResp) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pkg_contract_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFolderResp.ProtoReflect.Descriptor instead.
func (*GetFolderResp) Descriptor() ([]byte, []int) {
	return file_v1_pkg_contract_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetFolderResp) GetFile() []*File {
	if x != nil {
		return x.File
	}
	return nil
}

type SaveFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identification *Identification `protobuf:"bytes,1,opt,name=Identification,proto3" json:"Identification,omitempty"`
	File           *File           `protobuf:"bytes,2,opt,name=File,proto3" json:"File,omitempty"`
}

func (x *SaveFileReq) Reset() {
	*x = SaveFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pkg_contract_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveFileReq) ProtoMessage() {}

func (x *SaveFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pkg_contract_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveFileReq.ProtoReflect.Descriptor instead.
func (*SaveFileReq) Descriptor() ([]byte, []int) {
	return file_v1_pkg_contract_service_proto_rawDescGZIP(), []int{13}
}

func (x *SaveFileReq) GetIdentification() *Identification {
	if x != nil {
		return x.Identification
	}
	return nil
}

func (x *SaveFileReq) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

type RenameFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identification *Identification `protobuf:"bytes,1,opt,name=Identification,proto3" json:"Identification,omitempty"`
	RenameInfo     *RenameInfo     `protobuf:"bytes,2,opt,name=RenameInfo,proto3" json:"RenameInfo,omitempty"`
}

func (x *RenameFileReq) Reset() {
	*x = RenameFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pkg_contract_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenameFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameFileReq) ProtoMessage() {}

func (x *RenameFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pkg_contract_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameFileReq.ProtoReflect.Descriptor instead.
func (*RenameFileReq) Descriptor() ([]byte, []int) {
	return file_v1_pkg_contract_service_proto_rawDescGZIP(), []int{14}
}

func (x *RenameFileReq) GetIdentification() *Identification {
	if x != nil {
		return x.Identification
	}
	return nil
}

func (x *RenameFileReq) GetRenameInfo() *RenameInfo {
	if x != nil {
		return x.RenameInfo
	}
	return nil
}

type DeleteFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identification *Identification `protobuf:"bytes,1,opt,name=Identification,proto3" json:"Identification,omitempty"`
	Path           string          `protobuf:"bytes,2,opt,name=Path,proto3" json:"Path,omitempty"`
}

func (x *DeleteFileReq) Reset() {
	*x = DeleteFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pkg_contract_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileReq) ProtoMessage() {}

func (x *DeleteFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pkg_contract_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileReq.ProtoReflect.Descriptor instead.
func (*DeleteFileReq) Descriptor() ([]byte, []int) {
	return file_v1_pkg_contract_service_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteFileReq) GetIdentification() *Identification {
	if x != nil {
		return x.Identification
	}
	return nil
}

func (x *DeleteFileReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RecoverFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identification *Identification `protobuf:"bytes,1,opt,name=Identification,proto3" json:"Identification,omitempty"`
	Path           string          `protobuf:"bytes,2,opt,name=Path,proto3" json:"Path,omitempty"`
}

func (x *RecoverFileReq) Reset() {
	*x = RecoverFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pkg_contract_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecoverFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverFileReq) ProtoMessage() {}

func (x *RecoverFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pkg_contract_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverFileReq.ProtoReflect.Descriptor instead.
func (*RecoverFileReq) Descriptor() ([]byte, []int) {
	return file_v1_pkg_contract_service_proto_rawDescGZIP(), []int{16}
}

func (x *RecoverFileReq) GetIdentification() *Identification {
	if x != nil {
		return x.Identification
	}
	return nil
}

func (x *RecoverFileReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identification *Identification `protobuf:"bytes,1,opt,name=Identification,proto3" json:"Identification,omitempty"`
}

func (x *GetFileReq) Reset() {
	*x = GetFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pkg_contract_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileReq) ProtoMessage() {}

func (x *GetFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pkg_contract_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileReq.ProtoReflect.Descriptor instead.
func (*GetFileReq) Descriptor() ([]byte, []int) {
	return file_v1_pkg_contract_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetFileReq) GetIdentification() *Identification {
	if x != nil {
		return x.Identification
	}
	return nil
}

type GetFileResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File *File `protobuf:"bytes,1,opt,name=File,proto3" json:"File,omitempty"`
}

func (x *GetFileResp) Reset() {
	*x = GetFileResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_pkg_contract_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResp) ProtoMessage() {}

func (x *GetFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pkg_contract_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResp.ProtoReflect.Descriptor instead.
func (*GetFileResp) Descriptor() ([]byte, []int) {
	return file_v1_pkg_contract_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetFileResp) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

var File_v1_pkg_contract_service_proto protoreflect.FileDescriptor

var file_v1_pkg_contract_service_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x76, 0x31, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x76, 0x31, 0x22, 0x64, 0x0a, 0x0e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a,
	0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x4c, 0x0a, 0x10, 0x53, 0x74, 0x61,
	0x6e, 0x64, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x98, 0x01, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65,
	0x12, 0x3a, 0x0a, 0x0e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x48, 0x61, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x6f, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4d, 0x6f, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x69,
	0x7a, 0x65, 0x22, 0x72, 0x0a, 0x06, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x12, 0x3a, 0x0a, 0x0e,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x6f, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4d,
	0x6f, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x3a, 0x0a, 0x0a, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x50,
	0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4e, 0x65, 0x77, 0x50, 0x61,
	0x74, 0x68, 0x22, 0x71, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6c, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x3a, 0x0a, 0x0e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x76, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x22, 0x0a, 0x06, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x06, 0x46,
	0x6f, 0x6c, 0x64, 0x65, 0x72, 0x22, 0x97, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x3a, 0x0a, 0x0e, 0x49, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x0a, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x6e, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x52, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x6f, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4d, 0x6f, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0x61, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x12, 0x3a, 0x0a, 0x0e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x76, 0x31, 0x2e,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61,
	0x74, 0x68, 0x22, 0x62, 0x0a, 0x10, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x46, 0x6f, 0x6c,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x3a, 0x0a, 0x0e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x50, 0x61, 0x74, 0x68, 0x22, 0x4d, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x44, 0x69, 0x72,
	0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x12, 0x3a, 0x0a, 0x0e, 0x49, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x9a, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x44, 0x69, 0x72,
	0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x40, 0x0a, 0x10, 0x53, 0x74,
	0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x10, 0x53, 0x74, 0x61, 0x6e,
	0x64, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x07,
	0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x76, 0x31, 0x2e, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x07, 0x46, 0x6f, 0x6c, 0x64, 0x65,
	0x72, 0x73, 0x12, 0x1e, 0x0a, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x05, 0x46, 0x69, 0x6c,
	0x65, 0x73, 0x22, 0x5e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x12, 0x3a, 0x0a, 0x0e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x76, 0x31, 0x2e,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61,
	0x74, 0x68, 0x22, 0x2d, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x46, 0x69, 0x6c,
	0x65, 0x22, 0x67, 0x0a, 0x0b, 0x53, 0x61, 0x76, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x3a, 0x0a, 0x0e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x04,
	0x46, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x76, 0x31, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x7b, 0x0a, 0x0d, 0x52, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x3a, 0x0a, 0x0e, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x0a, 0x52, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x52, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x5f, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x3a, 0x0a, 0x0e, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x74, 0x68, 0x22, 0x60, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x3a, 0x0a, 0x0e, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x74, 0x68, 0x22, 0x48, 0x0a, 0x0a, 0x47, 0x65,
	0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x3a, 0x0a, 0x0e, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2b, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x46, 0x69, 0x6c,
	0x65, 0x32, 0xee, 0x04, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x12, 0x39, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6c, 0x64, 0x65,
	0x72, 0x12, 0x13, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6c,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x6e,
	0x64, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0c,
	0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x1a, 0x14, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0d, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x46, 0x6f, 0x6c,
	0x64, 0x65, 0x72, 0x12, 0x14, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72,
	0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x39, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x44, 0x69, 0x72, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12,
	0x13, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x72, 0x53, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x72,
	0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x12, 0x10, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x08,
	0x53, 0x61, 0x76, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x0f, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61,
	0x76, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x35, 0x0a, 0x0a, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x11, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x14, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x46, 0x69, 0x6c, 0x65, 0x12, 0x11, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61,
	0x6e, 0x64, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a,
	0x0b, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x14, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c,
	0x65, 0x12, 0x0e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x0f, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_pkg_contract_service_proto_rawDescOnce sync.Once
	file_v1_pkg_contract_service_proto_rawDescData = file_v1_pkg_contract_service_proto_rawDesc
)

func file_v1_pkg_contract_service_proto_rawDescGZIP() []byte {
	file_v1_pkg_contract_service_proto_rawDescOnce.Do(func() {
		file_v1_pkg_contract_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_pkg_contract_service_proto_rawDescData)
	})
	return file_v1_pkg_contract_service_proto_rawDescData
}

var file_v1_pkg_contract_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_v1_pkg_contract_service_proto_goTypes = []interface{}{
	(*Identification)(nil),   // 0: v1.Identification
	(*StandardResponse)(nil), // 1: v1.StandardResponse
	(*File)(nil),             // 2: v1.File
	(*Folder)(nil),           // 3: v1.Folder
	(*RenameInfo)(nil),       // 4: v1.RenameInfo
	(*CreateFolderReq)(nil),  // 5: v1.CreateFolderReq
	(*RenameFolderReq)(nil),  // 6: v1.RenameFolderReq
	(*DeleteFolderReq)(nil),  // 7: v1.DeleteFolderReq
	(*RecoverFolderReq)(nil), // 8: v1.RecoverFolderReq
	(*GetDirSchemaReq)(nil),  // 9: v1.GetDirSchemaReq
	(*GetDirSchemaResp)(nil), // 10: v1.GetDirSchemaResp
	(*GetFolderReq)(nil),     // 11: v1.GetFolderReq
	(*GetFolderResp)(nil),    // 12: v1.GetFolderResp
	(*SaveFileReq)(nil),      // 13: v1.SaveFileReq
	(*RenameFileReq)(nil),    // 14: v1.RenameFileReq
	(*DeleteFileReq)(nil),    // 15: v1.DeleteFileReq
	(*RecoverFileReq)(nil),   // 16: v1.RecoverFileReq
	(*GetFileReq)(nil),       // 17: v1.GetFileReq
	(*GetFileResp)(nil),      // 18: v1.GetFileResp
}
var file_v1_pkg_contract_service_proto_depIdxs = []int32{
	0,  // 0: v1.File.Identification:type_name -> v1.Identification
	0,  // 1: v1.Folder.Identification:type_name -> v1.Identification
	0,  // 2: v1.CreateFolderReq.Identification:type_name -> v1.Identification
	3,  // 3: v1.CreateFolderReq.Folder:type_name -> v1.Folder
	0,  // 4: v1.RenameFolderReq.Identification:type_name -> v1.Identification
	4,  // 5: v1.RenameFolderReq.RenameInfo:type_name -> v1.RenameInfo
	0,  // 6: v1.DeleteFolderReq.Identification:type_name -> v1.Identification
	0,  // 7: v1.RecoverFolderReq.Identification:type_name -> v1.Identification
	0,  // 8: v1.GetDirSchemaReq.Identification:type_name -> v1.Identification
	1,  // 9: v1.GetDirSchemaResp.StandardResponse:type_name -> v1.StandardResponse
	3,  // 10: v1.GetDirSchemaResp.Folders:type_name -> v1.Folder
	2,  // 11: v1.GetDirSchemaResp.Files:type_name -> v1.File
	0,  // 12: v1.GetFolderReq.Identification:type_name -> v1.Identification
	2,  // 13: v1.GetFolderResp.File:type_name -> v1.File
	0,  // 14: v1.SaveFileReq.Identification:type_name -> v1.Identification
	2,  // 15: v1.SaveFileReq.File:type_name -> v1.File
	0,  // 16: v1.RenameFileReq.Identification:type_name -> v1.Identification
	4,  // 17: v1.RenameFileReq.RenameInfo:type_name -> v1.RenameInfo
	0,  // 18: v1.DeleteFileReq.Identification:type_name -> v1.Identification
	0,  // 19: v1.RecoverFileReq.Identification:type_name -> v1.Identification
	0,  // 20: v1.GetFileReq.Identification:type_name -> v1.Identification
	2,  // 21: v1.GetFileResp.File:type_name -> v1.File
	5,  // 22: v1.FileManager.CreateFolder:input_type -> v1.CreateFolderReq
	6,  // 23: v1.FileManager.RenameFolder:input_type -> v1.RenameFolderReq
	7,  // 24: v1.FileManager.DeleteFolder:input_type -> v1.DeleteFolderReq
	8,  // 25: v1.FileManager.RecoverFolder:input_type -> v1.RecoverFolderReq
	9,  // 26: v1.FileManager.GetDirSchema:input_type -> v1.GetDirSchemaReq
	11, // 27: v1.FileManager.GetFolder:input_type -> v1.GetFolderReq
	13, // 28: v1.FileManager.SaveFile:input_type -> v1.SaveFileReq
	14, // 29: v1.FileManager.RenameFile:input_type -> v1.RenameFileReq
	15, // 30: v1.FileManager.DeleteFile:input_type -> v1.DeleteFileReq
	16, // 31: v1.FileManager.RecoverFile:input_type -> v1.RecoverFileReq
	17, // 32: v1.FileManager.GetFile:input_type -> v1.GetFileReq
	1,  // 33: v1.FileManager.CreateFolder:output_type -> v1.StandardResponse
	1,  // 34: v1.FileManager.RenameFolder:output_type -> v1.StandardResponse
	1,  // 35: v1.FileManager.DeleteFolder:output_type -> v1.StandardResponse
	1,  // 36: v1.FileManager.RecoverFolder:output_type -> v1.StandardResponse
	10, // 37: v1.FileManager.GetDirSchema:output_type -> v1.GetDirSchemaResp
	12, // 38: v1.FileManager.GetFolder:output_type -> v1.GetFolderResp
	1,  // 39: v1.FileManager.SaveFile:output_type -> v1.StandardResponse
	1,  // 40: v1.FileManager.RenameFile:output_type -> v1.StandardResponse
	1,  // 41: v1.FileManager.DeleteFile:output_type -> v1.StandardResponse
	1,  // 42: v1.FileManager.RecoverFile:output_type -> v1.StandardResponse
	18, // 43: v1.FileManager.GetFile:output_type -> v1.GetFileResp
	33, // [33:44] is the sub-list for method output_type
	22, // [22:33] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_v1_pkg_contract_service_proto_init() }
func file_v1_pkg_contract_service_proto_init() {
	if File_v1_pkg_contract_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_pkg_contract_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Identification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_pkg_contract_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StandardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_pkg_contract_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_pkg_contract_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Folder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_pkg_contract_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenameInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_pkg_contract_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFolderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_pkg_contract_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenameFolderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_pkg_contract_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFolderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_pkg_contract_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecoverFolderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_pkg_contract_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDirSchemaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_pkg_contract_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDirSchemaResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_pkg_contract_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFolderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_pkg_contract_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFolderResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_pkg_contract_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_pkg_contract_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenameFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_pkg_contract_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_pkg_contract_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecoverFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_pkg_contract_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_pkg_contract_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_pkg_contract_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_pkg_contract_service_proto_goTypes,
		DependencyIndexes: file_v1_pkg_contract_service_proto_depIdxs,
		MessageInfos:      file_v1_pkg_contract_service_proto_msgTypes,
	}.Build()
	File_v1_pkg_contract_service_proto = out.File
	file_v1_pkg_contract_service_proto_rawDesc = nil
	file_v1_pkg_contract_service_proto_goTypes = nil
	file_v1_pkg_contract_service_proto_depIdxs = nil
}
