// Code generated by MockGen. DO NOT EDIT.
// Source: consumer.go

// Package kafka is a generated GoMock package.
package kafka

import (
	context "context"
	reflect "reflect"

	domain "github.com/gobox-preegnees/file_manager/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockIStateSerivce is a mock of IStateSerivce interface.
type MockIStateSerivce struct {
	ctrl     *gomock.Controller
	recorder *MockIStateSerivceMockRecorder
}

// MockIStateSerivceMockRecorder is the mock recorder for MockIStateSerivce.
type MockIStateSerivceMockRecorder struct {
	mock *MockIStateSerivce
}

// NewMockIStateSerivce creates a new mock instance.
func NewMockIStateSerivce(ctrl *gomock.Controller) *MockIStateSerivce {
	mock := &MockIStateSerivce{ctrl: ctrl}
	mock.recorder = &MockIStateSerivceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStateSerivce) EXPECT() *MockIStateSerivceMockRecorder {
	return m.recorder
}

// SetState mocks base method.
func (m *MockIStateSerivce) SetState(arg0 context.Context, arg1 domain.SetStateReqDTO) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetState", arg0, arg1)
}

// SetState indicates an expected call of SetState.
func (mr *MockIStateSerivceMockRecorder) SetState(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetState", reflect.TypeOf((*MockIStateSerivce)(nil).SetState), arg0, arg1)
}
