version: "3"

networks:
  postgres:
    driver: bridge

services:
  postgres:
    container_name: my_postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 1s
    ports:
      - "5431:5432"
    # volumes:
    #   - ./data:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate
    restart: on-failure
    volumes:
        - ../migrations/test:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable", "up"]
    depends_on: 
        - postgres