// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package mock_repo is a generated GoMock package.
package mock_repo

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIStorage is a mock of IStorage interface.
type MockIStorage struct {
	ctrl     *gomock.Controller
	recorder *MockIStorageMockRecorder
}

// MockIStorageMockRecorder is the mock recorder for MockIStorage.
type MockIStorageMockRecorder struct {
	mock *MockIStorage
}

// NewMockIStorage creates a new mock instance.
func NewMockIStorage(ctrl *gomock.Controller) *MockIStorage {
	mock := &MockIStorage{ctrl: ctrl}
	mock.recorder = &MockIStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStorage) EXPECT() *MockIStorageMockRecorder {
	return m.recorder
}

// GetBatchFromDisk mocks base method.
func (m *MockIStorage) GetBatchFromDisk(path string) (*[]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBatchFromDisk", path)
	ret0, _ := ret[0].(*[]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBatchFromDisk indicates an expected call of GetBatchFromDisk.
func (mr *MockIStorageMockRecorder) GetBatchFromDisk(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBatchFromDisk", reflect.TypeOf((*MockIStorage)(nil).GetBatchFromDisk), path)
}

// SaveBatchOnDisk mocks base method.
func (m *MockIStorage) SaveBatchOnDisk(path string, data *[]byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBatchOnDisk", path, data)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveBatchOnDisk indicates an expected call of SaveBatchOnDisk.
func (mr *MockIStorageMockRecorder) SaveBatchOnDisk(path, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBatchOnDisk", reflect.TypeOf((*MockIStorage)(nil).SaveBatchOnDisk), path, data)
}
